services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL:?missing DEFAULT_EMAIL}
      ACME_CA_URI: ${ACME_CA_URI:?missing ACME_CA_URI}
    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
networks:
  default:
  nginx-proxy:
    name: nginx-proxy
  socket-proxy:
    external: true
